# Docker Compose Configuration with Hardware GPU Passthrough & Acceleration
# Run using: docker compose -f compose.gpu.yml up -d

services:
  windows:
    image: dockurr/windows
    container_name: windows
    environment:
      VERSION: "${VERSION:-win11}"
      DISK_SIZE: "64G"
      RAM_SIZE: "16G"
      CPU_CORES: "8"
      CPU_MODEL: "host"
      VGA: "virtio"
      TZ: "America/Bogota"
      AUDIO: "Y"
      USERNAME: "${USERNAME:-merxx}"
      PASSWORD: "${PASSWORD:-030414}"
      REGION: "en-us"
      KEYBOARD: "es-CO"
    devices:
      - /dev/kvm:/dev/kvm
      - /dev/dri:/dev/dri
      - /dev/net/tun:/dev/net/tun
    cap_add:
      - NET_ADMIN
    ports:
      - 8006:8006
      - 3389:3389/tcp
      - 3389:3389/udp
    volumes:
      - ./:/storage
      - /home/merxx:/shared/home
      - /mnt/vicioo:/shared/vicioo
    restart: always
    stop_grace_period: 2m
