services:
  windows:
    image: dockurr/windows
    container_name: windows
    environment:
      DISK_SIZE: "64G"
      RAM_SIZE: "16G"
      CPU_CORES: "8"
      CPU_MODEL: "host"
      TZ: "America/Bogota"
      AUDIO: "Y"
      USERNAME: "merxx"
      PASSWORD: "030414"
      REGION: "en-us"
      KEYBOARD: "es-CO"
    devices:
      - /dev/kvm
      - /dev/net/tun
    cap_add:
      - NET_ADMIN
    ports:
      - 8006:8006
      - 3389:3389/tcp
      - 3389:3389/udp
    volumes:
      - /home/merxx/Documents/experiments/windows_Docker-version:/storage
      - /home/merxx:/shared/home
      - /mnt/vicioo:/shared/vicioo
      - /mnt/vicioo/ISOS/en-us_windows_11_iot_enterprise_ltsc_2024_x64_dvd_f6b14814-ENGVersion.iso:/custom.iso
    restart: always
    stop_grace_period: 2m
